src/objects/MemberActivity__c.object
<CustomObject>
    <description>Object for tracking changes to Members</description>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MemberActivity</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MemberActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectActivity__c.object
<CustomObject>
    <description>Object for tracking Project Changes</description>
    <label>ProjectActivity</label>
    <nameField>
        <label>ProjectActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

src/objects/TaskActivity__c.object
<CustomObject>
    <description>Object for tracking changes within a task</description>
    <label>TaskActivity</label>
    <nameField>
        <label>TaskActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/objects/TaskAssigneeActivity__c.object
<CustomObject>
    <description>Object for tracking changes to task assignees</description>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TaskAssigneeActivity</label>
    <nameField>
        <label>TaskAssigneeActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskAssigneeActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaskCommentActivity__c.object
<CustomObject>
    <description>Object for tracking changes to task comments</description>
    <label>TaskCommentActivity</label>
    <nameField>
        <label>TaskCommentActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskCommentActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/classes/MessageLog.cls
/**
* @author Matias Menafra 1/11/2010
*/
public class MessageLog {
	
	
	/**
	* Constructor
	*/
	public MessageLog(){
	}
	
	/**
	*
	* @param sObject activity
	* @return String
	*/
	public String getMessage( sObject activity ){
		
		String message = '';
		
		if( activity instanceOf ProjectActivity__c ){
			ProjectActivity__c obj = ( ProjectActivity__c )activity;
			message = this.messageProject( obj );
		}
		
		if( activity instanceOf MemberActivity__c ){
			MemberActivity__c obj = ( MemberActivity__c )activity;
			message = this.messageMember( obj );
		}
		
		if( activity instanceOf TaskActivity__c ){
			TaskActivity__c obj = ( TaskActivity__c )activity;
			message = this.messageTask( obj );
		}
		
		if( activity instanceOf TaskAssigneeActivity__c ){
			TaskAssigneeActivity__c obj = ( TaskAssigneeActivity__c )activity;
			message = this.messageAssignee(obj);
		}
		
		if( activity instanceOf TaskCommentActivity__c ){
			TaskCommentActivity__c obj = ( TaskCommentActivity__c )activity;
			message = this.messageTaskComment( obj );
		}
		/*
		if(activity instanceOf AttachmentActivity__c){
		
		}
		*/
		
		return message;
	}
	
	/**
	*
	* @param ProjectActivity__c activity
	* @return String
	*/
	private String messageProject( ProjectActivity__c activity ){
		
		String msg = '';
		
		if( activity.ChangeType__c == 1 ){
			msg = '';
		}
		
		if( activity.ChangeType__c == 2 ){
			msg = '';
		}
		
		return msg;
	}
	
	/**
	*
	* @param TaskActivity__c activity
	* @return String
	*/
	private String messageTask( TaskActivity__c activity ){
		return '';
	}
	
	/**
	*
	* @param TaskAssigneeActivity__c activity
	* @return String
	*/
	private String messageAssignee( TaskAssigneeActivity__c activity ){
		return '';
	}
	
	/**
	*
	* @param TaskCommentActivity__c activity
	* @return String
	*/
	private String messageTaskComment( TaskCommentActivity__c activity ){
		return '';
	}
	
	/**
	*
	* @param MemberActivity__c activity
	* @return String
	*/
	private String messageMember( MemberActivity__c activity ){
		return '';
	}
	
	/**
	*
	* @param 
	* @return String
	*/
	private String messageAttachment(){
		return '';
	}
}