src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>DaysInWorkWeek__c</fullName>
        <label>Days in a work week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Set how you want see the Duration field, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WorkingHours__c</fullName>
        <label>Working hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Profile__c</fullName>
        <description>Profile</description>
        <label>Profile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectProfile__c.object
<CustomObject>
    <description>ProjectProfile</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Project Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DAOProject.cls
/**
* @author Andres Canavesi
* @dataCreated 12/15/2009
*/
public class DAOProject {
	
	/**
	* Constructor
	*/
	public DAOProject(){}
	
	/**
	* @param projectId
	* @return members
	*/
	public List<ProjectMember__c> getMembers( String projectId ){
		
		List<ProjectMember__c> members = new List<ProjectMember__c>();
		
		members = [select t.Project__c, t.User__r.Name, t.User__r.IsActive, t.Name, t.User__c, t.Id 
	  	 		   from ProjectMember__c t 
	  	 		   where t.Project__c =: projectId 
	  	 		   and t.User__r.IsActive != false];
	  	 		   
	    return members;
		
	}
	
	/** Return project members, order by CreateDate
	* @param projectId
	* @return members
	*/
	public List<ProjectMember__c> getMembersToWidget (String idProject){
		List<ProjectMember__c> members = new List<ProjectMember__c>();
		members = [Select Id, OwnerId,  Name, CreatedDate, Profile__c, Project__c, User__c,  Profile__r.Name 
					from ProjectMember__c where Project__c =: idProject and User__r.IsActive != false
					Order By CreatedDate desc limit 10];
		return members;
	}
	
	/**
	* @param projectId
	* @param project
	*/
	public Project getInfo( String projectId ){
		
		Project2__c project2 = new Project2__c();
		Project project = new Project();
		
		project2 = [select id, name, description__c, priority__c, displayDuration__c, DaysInWorkWeek__c, WorkingHours__c 
		            from Project2__c 
		            where id =: projectId 
		            limit 1 ];
		
		project.id = project2.id;
		project.name = project2.name;
		project.description = project2.description__c;
		project.priority = project2.priority__c;
		project.displayDuration = project2.displayDuration__c;
		project.daysWorkWeek = project2.DaysInWorkWeek__c;
		project.setWorkingHours( project2.WorkingHours__c );
		
		return project;
	}
	
	/**
	* @param projectId
	* @return isProjectAdministrator
	*/
	public Boolean isProjectAdministrator( String projectId ){
		
		List<Project2__c> project = [select Id
					       			 from Project2__c
					                 where OwnerId =: Userinfo.getUserId() 
					                 and id =:projectId
					       			 limit 1];
							 
		if(project.size() > 0){
			return true;
		}
		
		return false;
	}
	
	/**
	* 
	* @param taskId
	* @return task
	*/
	public ApexPages.StandardSetController searchForProjects( String searchTerm, String namespace ){
		
		String searchQ = '%'+ searchTerm +'%';
		
		ApexPages.StandardSetController searchResults = new ApexPages.StandardSetController( Database.getQueryLocator( [Select Id, Name, Description__c From Project2__c Where Name LIKE :searchQ OR Description__c LIKE :searchQ ] ) );
		
		if( searchResults.getResultSize() == 0 ){
			return new ApexPages.StandardSetController( new List<Project2__c>() );
		}
		
		return searchResults;	
	}
	
	
	/**
	* @param void
	* @return Map<String,Id>
	*/
	public Map<String,Id> idProjectProfile(){
		Map<String,Id> projectProfile= new Map<String,Id>();
		for (ProjectProfile__c projectMember : [SELECT Name,Id FROM ProjectProfile__c 
								WHERE Name = 'Project Administrator' or Name = 'Member Profile']) {
			projectProfile.put(projectMember.Name,projectMember.Id);
		}
		return projectProfile;
	}
	
}