src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TaskAssignee.cls
/**
* @author Matias Menafra 
* @createdDate 12/18/2009
*/
public class TaskAssignee {
	
	public String Id			{ set; get; }
	public String name			{ set; get; }
	public String project 		{ set; get; }
	public String projectTask 	{ set; get; }
	public String user			{ set; get; }
	
	/**
	* Constructor
	*/
	public TaskAssignee(){
	
	}
	
	/**
	* Test ProjectDetailController
	*/
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();

		TaskAssignee tA = new TaskAssignee();
		
		tA.id 			= GenerateEnvironmentTest.assi.Id;
		tA.name 		= GenerateEnvironmentTest.assi.name;
		tA.project 		= GenerateEnvironmentTest.assi.project__c;
		tA.projectTask 	= GenerateEnvironmentTest.assi.projectTask__c;
		tA.user 		= UserInfo.getUserId();
    	
		tA.id 			= tA.id;
		tA.name 		= tA.name;
		tA.project 		= tA.project;
		tA.projectTask 	= tA.projectTask;
		tA.user 		= tA.user;

    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }		
}