src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>Access__c</fullName>
        <description>Project Access</description>
        <inlineHelpText>Open - Anyone can join. Anyone can see the Project

Close - Administrator must invite users to join. Anyone can see the Project

Private -  This Project will not appear in search. Membership is by invitation only. Only members can see the Project.</inlineHelpText>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DaysInWorkWeek__c</fullName>
        <label>Days in a work week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Set how you want see the Duration field, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipLabel>Project (NewMemberProfile)</relationshipLabel>
        <relationshipName>Project1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PublicProfile__c</fullName>
        <label>PublicProfile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipLabel>Project</relationshipLabel>
        <relationshipName>Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkingHours__c</fullName>
        <label>Working hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TriggersTest.cls
/**
*@author Miguel Soares @ 04/16/2009
*/
@isTest private class TriggersTest {
	
	/**
	* Test1
	*@void
    *@static
	*/
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();

		upsert GenerateEnvironmentTest.project;
		upsert GenerateEnvironmentTest.member;
		upsert GenerateEnvironmentTest.task;

    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }         	

	/**
	* Test2
	*@void
    *@static
	*/
    static testMethod void myUnitTest2(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();

		try{
			upsert GenerateEnvironmentTest.pred;
		}catch (Exception e){}
		
		upsert GenerateEnvironmentTest.assi;

    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }         	

       	
    /**
	* Test2
	*@void
    *@static
	*/
    static testMethod void myUnitTest3(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
		
		upsert GenerateEnvironmentTest.assi;
        delete GenerateEnvironmentTest.assi;
        try{
 			delete GenerateEnvironmentTest.pred;
        }catch (Exception e){}
        
		delete GenerateEnvironmentTest.task;
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }   
           	
  	/**
	* Test3
	*@void
    *@static 
	*/
    static testMethod void myUnitTest4(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	
		delete GenerateEnvironmentTest.member;
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }   

  	/**
	* Test4
	*@void
    *@static
	*/
    static testMethod void myUnitTest5(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	
		delete GenerateEnvironmentTest.project;
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }   

  	/**
	* Test6
	*@void
    *@static
	*/
    static testMethod void myUnitTest6(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	
		Project2__c p = new Project2__c();
		p = GenerateEnvironmentTest.project; // Old p
		// New p
		p.PublicProfile__c 		= 	null;
		p.NewMemberProfile__c	=	null;
		update p;	
		
		p = GenerateEnvironmentTest.project; // Old p		
		// New p
		p.PublicProfile__c 		= 	null;
		update p;	
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }   
  	/**
	* Test6
	*@void
    *@static
	*/
    static testMethod void myUnitTest7(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();	

		Project2__c project = new Project2__c();
        project.name = 'Project 1 name';
        project.description__c = 'Open';
        project.Access__c = 'Description ...';
        project.priority__c = 'High';
        project.DisplayDuration__c = 'Days';
        project.WorkingHours__c = 8.0;
        project.DaysInWorkWeek__c = '5';
        project.Type__c = 'open';
        //project.PublicProfile__c = profList[ 0 ].Id;
        //project.NewmemberProfile__c = profList[ 1 ].Id;
		insert project;
        project.PublicProfile__c = GenerateEnvironmentTest.profList[ 0 ].Id;
		update project;
		
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }   

}