src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectTaskPred__c.object
<CustomObject>
    <fields>
        <fullName>Lag_Time__c</fullName>
        <label>Lag Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lag_Type__c</fullName>
        <label>Lag Type</label>
        <picklist>
            <picklistValues>
                <fullName>Finish-to-Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start-to-Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finish-to-Finish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start-to-Finish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipLabel>Project Task Predecessors</relationshipLabel>
        <relationshipName>Project_Task_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <label>Predecessor</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipLabel>Project Task Predecessors (Predecessor)</relationshipLabel>
        <relationshipName>Project_Task_Predecessors1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task Predecessor</label>
    <nameField>
        <label>Project Task Predecessor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task Predecessors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTaskPred__c.object
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Project Task Predecessors</relationshipLabel>
        <relationshipName>Project_Task_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/TaskDependenciesTest.cls
@isTest private class TaskDependenciesTest {

	static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	
    	TaskDependencies td = new TaskDependencies( GenerateEnvironmentTest.project.id );
    	
    	ProjectTask__c task = GenerateEnvironmentTest.task;
    	ProjectTask__c task2 = GenerateEnvironmentTest.task;
    	ProjectTask__c mile = GenerateEnvironmentTest.mile;
    	List<ProjectTaskPred__c> listPtp = new List<ProjectTaskPred__c>();    	
		ProjectTaskPred__c ptp = new ProjectTaskPred__c();
			ptp.Project__c = GenerateEnvironmentTest.project.id;
			ptp.Predecessor__c = task.id;
			ptp.Parent__c = task2.id;
			ptp.Lag_Time__c = 0;
			ptp.Lag_Type__c = 'Finish-to-Start';
		listPtp.add(ptp);
		 ptp = new ProjectTaskPred__c();
			ptp.Project__c = GenerateEnvironmentTest.project.id;
			ptp.Predecessor__c = task2.id;
			ptp.Parent__c = mile.id;
			ptp.Lag_Time__c = 0;
			ptp.Lag_Type__c = 'Finish-to-Start';
		listPtp.add(ptp);

		insert listPtp;
    	
    	
    	td.goGoGo( task, task2 );
    	
    	task2.startDate__c = Date.valueOf(task2.startDate__c).addDays( -10 );    	 
    	td.goGoGo( task, task2 );
    	
    	ProjectTask__c taskAux = task.clone(); 
    	taskAux.startDate__c = Date.valueOf(task.startDate__c).addDays( 4 );    	 
    	taskAux.endDate__c   = Date.valueOf(task.startDate__c).addDays( 4 );    	 
    	td.movingTask(task, taskAux);
    	
    	td.changeLag( listPtp[ 0 ]);
				
		 ptp = new ProjectTaskPred__c();
			ptp.Project__c = GenerateEnvironmentTest.project.id;
			ptp.Predecessor__c = mile.id;
			ptp.Parent__c = task.id;
			ptp.Lag_Time__c = 0;
			ptp.Lag_Type__c = 'Finish-to-Start';
		try{
			td.checkCyclicDependencie(task.id, task2.id);
			//td.checkCyclicDependencie(task.id, mile.id);
			insert ptp;
			td.checkCyclicDependencie(task.id, mile.id);	
			td.InsertinfPred( listPtp[ 0 ]);
		}catch( Exception e ){}
 		
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }
         	
}