src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProjectOverlayNewMilestoneControllerTest.cls
/**
*@author Miguel Soares @ 04/14/2009
*/
@isTest private class ProjectOverlayNewMilestoneControllerTest {
	
	/**
	* Test  ProjectOverlayNewMilestoneController
	*@void
    *@static
	*/
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
		
		System.currentPageReference().getParameters().put( 'id', GenerateEnvironmentTest.project.Id );
		ProjectOverlayNewMilestoneController mileC = new ProjectOverlayNewMilestoneController();
    	
    	mileC.setCurrentProjectId( GenerateEnvironmentTest.project.Id );
    	
    	ProjectTask__c newTask = new ProjectTask__c();
    	newTask.StartDate__c = Date.today();
    	newTask.DurationUI__c = '1';
    	mileC.setNewProyect( newTask );
    	
    	mileC.insertMilestone();

    	mileC.dummyRefresh();

    	mileC.getUserLocale();
    	mileC.getCurrentProject();
    	mileC.getProjectMembers();
    	mileC.getProjectMember();
    	mileC.getTask();
    	mileC.getCurrentProjectId();
    	
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    } 
}