src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>Access__c</fullName>
        <description>Project Access</description>
        <inlineHelpText>Open - Anyone can join. Anyone can see the Project

Close - Administrator must invite users to join. Anyone can see the Project

Private -  This Project will not appear in search. Membership is by invitation only. Only members can see the Project.</inlineHelpText>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DaysInWorkWeek__c</fullName>
        <label>Days in a work week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Set how you want see the Duration field, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewMemberProfile__c</fullName>
        <label>NewMemberProfile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipLabel>Project (NewMemberProfile)</relationshipLabel>
        <relationshipName>Project1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PublicProfile__c</fullName>
        <label>PublicProfile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipLabel>Project</relationshipLabel>
        <relationshipName>Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkingHours__c</fullName>
        <label>Working hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Profile__c</fullName>
        <description>Profile</description>
        <label>Profile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectProfile__c.object
<CustomObject>
    <description>ProjectProfile</description>
    <fields>
        <fullName>CreateProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CreateProjectTasks</description>
        <label>CreateProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ManageProjectTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ManageProjectTasks</description>
        <label>ManageProjectTasks</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectTaskPred__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Parent</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipLabel>Project Task Predecessors</relationshipLabel>
        <relationshipName>Project_Task_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task Predecessor</label>
    <nameField>
        <label>Project Task Predecessor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task Predecessors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTaskPred__c.object
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>Project Task Predecessors</relationshipLabel>
        <relationshipName>Project_Task_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/TaskComment__c.object
<CustomObject>
    <description>Task related comments</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Project Task</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipLabel>TaskComments</relationshipLabel>
        <relationshipName>TaskComments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskComment</label>
    <nameField>
        <label>TaskComment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskComments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenerateEnvironmentTest.cls
/**
* @author: Miguel Soares @ 07-04-2009
*/
public class GenerateEnvironmentTest {
	
    public static Project2__c project  		= new Project2__c();
    public static Project2__c project2 		= new Project2__c();
    public static Project2__c project3 		= new Project2__c();

    public static ProjectMember__c member  	= new ProjectMember__c();
    public static ProjectMember__c member2 	= new ProjectMember__c();

    public static ProjectTask__c task  		= new ProjectTask__c();
    public static ProjectTask__c task2 		= new ProjectTask__c();
    public static ProjectTask__c mile  		= new ProjectTask__c();
    
    public Static TaskComment__c comment	= new TaskComment__c();
    public Static TaskComment__c comment2	= new TaskComment__c();
    public Static TaskComment__c comment3	= new TaskComment__c();
    
    public static ProjectTaskPred__c pred 	= new ProjectTaskPred__c();
    
    public static ProjectAssignee__c assi 	= new ProjectAssignee__c();
    public static ProjectAssignee__c assi2 	= new ProjectAssignee__c();
    public static ProjectAssignee__c assi3 	= new ProjectAssignee__c();

    public static Attachment avatar 		= new Attachment(Name = 'avatar',ContentType = 'foo', Body = Crypto.generateMac('HMacSHA1', Blob.valueOf('String'), Blob.valueOf('String')));
    public static User user					= new User();
    
    public static List<ProjectProfile__c> profList = new List<ProjectProfile__c>();
	
	/**
    * Generate enviroment to test
    */
    public static testMethod void gen(){

        ProjectUtil.setIsTest( true );
        
        user = [ SELECT Id, Name FROM User LIMIT 1 ];
                
        // Creating profiles
        ProjectProfile__c projectProfile = new ProjectProfile__c();
        projectProfile.Name 					= 'Member Profile';
        projectProfile.ManageProjectTasks__c 	= false;
        projectProfile.CreateProjectTasks__c 	= true;
        profList.add( projectProfile );
            
        projectProfile = new ProjectProfile__c();
        projectProfile.Name 					= 'Public Profile';
        projectProfile.ManageProjectTasks__c 	= false;
        projectProfile.CreateProjectTasks__c 	= false;
        profList.add( projectProfile );

        projectProfile = new ProjectProfile__c();
        projectProfile.Name 					= 'Project Administrator';
        projectProfile.ManageProjectTasks__c 	= true;
        projectProfile.CreateProjectTasks__c 	= true;
        profList.add( projectProfile );
        
        insert profList;

        project.name 					= 'Project open';
        project.description__c 			= 'Open';
        project.Access__c 				= 'Description ...';
        project.priority__c 			= 'High';
        project.DisplayDuration__c 		= 'Days';
        project.WorkingHours__c 		= 8.0;
        project.DaysInWorkWeek__c 		= '5';
        project.Type__c 				= 'open';
        project.PublicProfile__c 		= profList[ 0 ].Id;
        project.NewmemberProfile__c 	= profList[ 1 ].Id;
        
        project2.name 					= 'Project Closed';
        project2.description__c 		= 'Description ...';
        project2.Access__c 				= 'Closed';
        project2.priority__c 			= 'Medium';
        project2.DisplayDuration__c 	= 'Days';
        project2.WorkingHours__c 		= 8.0;
        project2.DaysInWorkWeek__c 		= '5';
        project2.Type__c 				= 'closed';
    
        project3.name 					= 'Project Private';
        project3.description__c 		= 'Description ...';
        project3.Access__c 				= 'Private';
        project3.DisplayDuration__c 	= 'Days';
        project3.WorkingHours__c 		= 8.0;
        project3.DaysInWorkWeek__c 		= '5';
        project3.priority__c 			= 'Medium';
        project3.Type__c 				= 'private';
    
        List<Project2__c> projList = new List<Project2__c>();
        projList.add( project );
        projList.add( project2 );
        
        insert projList;

        avatar.parentId = projList[ 0 ].Id;
        insert avatar;
        
        projList[ 0 ].picture__c = avatar.id;
        update projList[ 0 ];

        // Owner for all projects inserted is the same. 
        // This project members are to delete
        member.User__c    = UserInfo.getUserId();
        member.Project__c = project.Id;
        member.Name		  = 'Member 1';	
        member.Profile__c = project.NewMemberProfile__c; 
        
        member2.User__c    = UserInfo.getUserId();
        member2.Project__c = project.Id;
        member.Name		  = 'Member 2';	
        member2.Profile__c = project.NewMemberProfile__c; 
        
        List<ProjectMember__c> memlist = new List<ProjectMember__c>();
        memList.add( member );
        memList.add( member2 );
        insert memList;
    
        // Tasks
        task.Name 			= 'task 1';
        task.Project__c 	= project.id;
        task.StartDate__c 	= Date.today();
        task.EndDate__c 	= Date.today();
        task.Notes__c		= 'fjfkl dsjfklds jfiosdj flksdj flkaj klfjs dlkf sjl';
        task.DurationUI__c 	= '2';
        
	    mile.Name 					= 'milestone';
	    mile.Project__c 			= project.id;
        mile.StartDate__c 			= Date.today();
        mile.EndDate__c 	= Date.today();
        mile.DurationUI__c 			= '2';
        mile.PercentCompleted__c 	= 55;
        mile.Milestone__c 			= true;
        
        task2.Name 				= 'task 2';
        task2.Project__c 		= project2.id;
        task2.StartDate__c 		= Date.today();
        task2.Notes__c			= 'fjfkl dsjfklds jfiosdj flksdj flkaj klfjs dlkf sjl';
        task2.EndDate__c 		= Date.today();
        task2.DurationUI__c 	= '2';      
        
        List<ProjectTask__c> taskList = new List<ProjectTask__c>();
        taskList.add( task );
        taskList.add( task2 );
        taskList.add( mile );
        
        insert taskList;
		
		  List<TaskComment__c> commentList = new List<TaskComment__c>();
		//Adding comments to tasks
		comment.Body__c = 'comment number 1';
		comment.Task__c = task.Id;
		comment2.Body__c = 'comment number 2';
		comment2.Task__c = task2.Id;
		comment3.Body__c = 'comment number 3';
		comment3.Task__c = task.Id;
		
		commentList.add( comment );
		commentList.add( comment2 );
		commentList.add( comment3 );
		
		insert commentList;
		
        pred.Name 		= 'Pred';
        pred.Parent__c 	= task.id;
        pred.Project__c = project.id;
        
        // Assignees
        assi.Name 				= 'Assignee 1';
        assi.Project__c 		= project.Id;
        assi.ProjectTask__c 	= task.Id;
        assi.User__c 			= member.User__c;
        
        assi2.Name			 	= 'Assignee 2';
        assi2.Project__c 		= project.Id;
        assi2.ProjectTask__c 	= task.Id;
        assi2.User__c 			= member.User__c;

        assi2.Name 				= 'Assignee 3';
        assi2.Project__c 		= project2.Id;
        assi2.ProjectTask__c 	= task.Id;
        assi2.User__c 			= member2.User__c;
    }
}