src/objects/ProjectSubscription__c.object
<CustomObject>
    <description>The Proyect Subscription Object</description>
    <fields>
        <fullName>ProjectMemberJoinLeave__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If a Member join leave from Project</description>
        <label>ProjectMemberJoinLeave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If i have proyect task assigned to me</description>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If project task has changed</description>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Project task has been deleted</description>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectSubscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Subscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Subscription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectSubscribersEmailServicesTest.cls
/**
*@author Miguel Soares @ 04/14/2009
*/
@isTest private class ProjectSubscribersEmailServicesTest {
	
	/**
	* Test  ProjectSubscribersEmailServices
	*/
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	
    	ProjectSubscribersEmailServices es = new ProjectSubscribersEmailServices();
    	
    	
    	es.setIsTaskEdit( true );
    	
    	List<String> lPM = new List<String>();
    	lPM.add( GenerateEnvironmentTest.member.Id );
    	lPM.add( GenerateEnvironmentTest.member2.Id );
    	es.sendMemberJoinLeave( lPM, 'join' );
    	es.sendMemberJoinLeave( lPM, 'leave' );
    	
    	es.setIsTest( true );
    	es.setIsTaskEdit( true );
		List<String> lPA = new List<String>();
		lPA.add( GenerateEnvironmentTest.assi.Id );    	
		lPA.add( GenerateEnvironmentTest.assi2.Id );    	
		lPA.add( GenerateEnvironmentTest.assi3.Id );    	
    	es.sendMailForTaskAssigned( lPA );
    	
    	List<String> lPT = new List<String>();
    	lPT.add( GenerateEnvironmentTest.task.Id );
    	lPT.add( GenerateEnvironmentTest.task2.Id );
    	es.sendMailForTaskChanged( lPT );
    	es.sendMailForTaskDeleted( lPT );


		ProjectSubscription__c sub = new ProjectSubscription__c();
		sub.Project__c = GenerateEnvironmentTest.project.Id;
		sub.ProjectMemberJoinLeave__c = true;
		sub.ProjectTaskAssignedToMe__c = true;
		sub.ProjectTaskAssignToMeChanged__c = true;
		sub.ProjectTaskChanged__c = true;
		sub.ProjectTaskDeleted__c = true;
		sub.User__c = GenerateEnvironmentTest.us.Id;
		List<ProjectSubscription__c> psb = new List<ProjectSubscription__c>();
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		psb.add( sub );
		ProjectSubscribersEmailServices.alreadySent = true;
		es.genAddress( psb, '', '' );    	
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    } 
}