src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describe task status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MyTasksAndMilestonesController.cls
public with sharing class MyTasksAndMilestonesController {
	
	private id currentUser;
	private id currentProject;
	
	public List<Task> tasks { set; get; }
	public List<Task> milestones { set; get; }

	public MyTasksAndMilestonesController(){
		this.tasks 			= new List<Task>();
		this.milestones 	= new List<Task>();
		this.currentUser 	= UserInfo.getUserId();
		this.currentProject = System.currentPageReference().getParameters().get( 'id' );
		this.selectTaskToShow();
	}
	
	private void selectTaskToShow(){
		List<ProjectAssignee__c> localTasks = new List<ProjectAssignee__c>();
		List<ProjectAssignee__c> localMilestones = new List<ProjectAssignee__c>();
		
		localTasks = [  SELECT id, project__c, project__r.name, projectTask__r.name, projectTask__r.status__c, projectTask__r.priority__c, projectTask__r.startDate__c, projectTask__r.endDate__c, projectTask__r.percentCompleted__c, projectTask__r.milestone__c, ProjectTask__r.DurationUI__c
							FROM ProjectAssignee__c 
							WHERE projectTask__r.milestone__c = false AND User__c =: this.currentUser AND projectTask__r.status__c != 'Close'
							ORDER BY projectTask__r.endDate__c DESC  LIMIT 5];
		
		localMilestones = [  SELECT id, project__c, project__r.name, projectTask__r.name, projectTask__r.status__c, projectTask__r.priority__c, projectTask__r.startDate__c, projectTask__r.endDate__c, projectTask__r.percentCompleted__c, projectTask__r.milestone__c, ProjectTask__r.DurationUI__c
								FROM ProjectAssignee__c 
								WHERE projectTask__r.milestone__c = true AND User__c =: this.currentUser AND projectTask__r.status__c != 'Close'
								ORDER BY projectTask__r.endDate__c DESC  LIMIT 5];
								
		this.tasks = ObjectFormatter.formatAssigneeTask( localTasks );
		this.milestones = ObjectFormatter.formatAssigneeTask( localMilestones );
	}
}