src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentTask__c</fullName>
        <description>ParentTask</description>
        <label>ParentTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BigListOfTasksTest.cls
@isTest private class BigListOfTasksTest {
	
	public static ProjectTask__c pt;
	public static ProjectTask__c pt1;
	public static ProjectTask__c pt2;
	
	public static testMethod void generateEnvironment(){
		
		GenerateEnvironmentTest.gen();
		List<ProjectTask__c> tsks = new List<ProjectTask__c>();
		
		pt = new ProjectTask__c();
			pt.Name = 'Padre11';
			pt.StartDate__c = System.today();
			pt.DurationUI__c = '2';
		        pt.Project__c = GenerateEnvironmentTest.project.Id;
			pt.Priority__c ='Medium';
			pt.PercentCompleted__c = 0.0;
		 tsks.add( pt );
		
		pt1 = new ProjectTask__c();
			pt1.Name = 'Padre22';
			pt1.StartDate__c = System.today();
			pt1.DurationUI__c = '2';
		        pt1.Project__c =  GenerateEnvironmentTest.project.Id;
			pt1.Priority__c ='Medium';
			pt1.PercentCompleted__c = 0.0;
			pt1.ParentTask__c = pt.Id;
		tsks.add( pt1 );
		
		pt2 = new ProjectTask__c();
			pt2.Name = 'Padre22';
			pt2.StartDate__c = System.today();
			pt2.DurationUI__c = '2';
		        pt2.Project__c =  GenerateEnvironmentTest.project.Id;
			pt2.Priority__c ='Medium';
			pt2.Milestone__c = true;
			pt2.PercentCompleted__c = 0.0;
			pt2.ParentTask__c = pt.Id;
		tsks.add( pt2 );
		
		insert tsks;		
	}
	
	 public static testMethod void myUnitTest(){
			
		generateEnvironment();
		BigListOfTasks bigListOfTask = new BigListOfTasks(GenerateEnvironmentTest.project.Id);
		
    	Test.startTest();
		
		ProjectTask__c aux = BigListOfTasks.get(0);
		ProjectTask__c pt3 = new ProjectTask__c();
		BigListOfTasks.add(pt3);
		
		BigListOfTasks.setById(pt2);
		
		ProjectTask__c aux2 = BigListOfTasks.getById(pt.Id);
		
		List<ProjectTask__c> lst = BigListOfTasks.getByParentId(pt.Id);
		
		Integer size = BigListOfTasks.size();
		Test.stopTest();		 
	 }
}