trunk/src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MemberActivity__c.object
<CustomObject>
    <description>Object for tracking changes to Members</description>
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>MemberActivities</relationshipLabel>
        <relationshipName>MemberActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MemberActivity</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MemberActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectActivity__c.object
<CustomObject>
    <description>Object for tracking Project Changes</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>ProjectActivity</label>
    <nameField>
        <label>ProjectActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>ProjectActivities</relationshipLabel>
        <relationshipName>ProjectActivities</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

src/classes/ActivityWidgetController.cls
/**
* @author Matias Menafra 
* @createdDate 1/15/2010
*/
public class ActivityWidgetController {
	
	public String 			projectId 		{ set; get; }
	private MessageLog 		messageObj; 			
	private List<Activity> 	resultActivities; 
	
	/**
	* Constructor
	*/
	public ActivityWidgetController(){
		
		this.messageObj 		= new MessageLog();
		this.resultActivities 	= new List<Activity>();
		
		//call to method for getting and parsing all activities for a project
		this.parseActivities();
	}
	
	/**
	* Method which collects the latest 10 project activities and parses them.
	*/
	public void parseActivities(){
		
		List<Activity__c> allActivities = new List<Activity__c>();
		allActivities = DAOFactory.getInstance().getActivityForProjectWidget( this.projectId );
		
		for( Activity__c row : allActivities ){
			
			Activity auxActivity = new Activity();
			
			auxActivity.modifiedBy 	= row.ModifiedBy__c;
			auxActivity.action 		= row.Action__c;
			auxActivity.timestamp	= row.TimeStamp__c;
			
			if (row.ProjectActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.ProjectActivities__r[0].ChangeType__c;
				auxActivity.message 	= this.messageObj.getMessage( row.ProjectActivities__r[0] );
			}
			
			if( row.MemberActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.MemberActivities__r[0].ChangeType__c;
				auxActivity.message 	= this.messageObj.getMessage( row.MemberActivities__r[0] );
			}
			
			if( row.TaskActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskActivites__r[0].ChangeType__c;
				auxActivity.message 	= this.messageObj.getMessage( row.TaskActivites__r[0] );
			}
			
			if( row.TaskAssigneeActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskAssigneeActivites__r[0].ChangeType__c;
				auxActivity.message 	= this.messageObj.getMessage( row.TaskAssigneeActivites__r[0] );
			}
			
			if(row.TaskCommentActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskCommentActivites__r[0].ChangeType__c;
				auxActivity.message 	= this.messageObj.getMessage( row.TaskCommentActivites__r[0] );
			}
			
			auxActivity.setImagePath();
			auxActivity.setHeader();
			
			this.resultActivities.add( auxActivity );
		}
	}
	
	/**
	* Getter for returning the list with the 10 latest activities for the widget.
	* @return resultActivities
	*/
	public List<Activity> getResultActivities(){
		return this.resultActivities;
	}
	
	/**
    * Test 
    */
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
		
		
    	Test.stopTest();
		ProjectUtil.setIsTest( false );    	
    }
}