trunk/src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/MemberActivity__c.object
<CustomObject>
    <description>Object for tracking changes to Members</description>
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>MemberActivities</relationshipLabel>
        <relationshipName>MemberActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MemberActivity</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MemberActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectActivity__c.object
<CustomObject>
    <description>Object for tracking Project Changes</description>
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>ProjectActivities</relationshipLabel>
        <relationshipName>ProjectActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ProjectActivity</label>
    <nameField>
        <label>ProjectActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectActivity__c.object
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>

src/objects/ProjectActivity__c.object
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>

trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration</description>
        <label>Duration Display</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <displayFormat>#{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/ObjectFormatter.cls
/**
* @author Matias Menafra
* @dataCreated 01/22/2010
*/
public class ObjectFormatter {

	/**
	* Constructor
	*/
	//public ObjectFormatter(){
	
	//}
	
	/**
	* 
	*
	*/
	public static List<Activity> formatProjectActivities( List<Activity__c> activityList ){
		
		MessageLog messageObj = new MessageLog();
		List<Activity> projectActivities = new List<Activity>();
		
		for( Activity__c row : activityList ){
			
			Activity auxActivity = new Activity();
			
			auxActivity.modifiedBy 	= row.ModifiedBy__c;
			auxActivity.action 		= row.Action__c;
			auxActivity.timestamp	= row.TimeStamp__c;
			
			if (row.ProjectActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.ProjectActivities__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.ProjectActivities__r[0] );
			}
			
			if( row.MemberActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.MemberActivities__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.MemberActivities__r[0] );
			}
			
			if( row.TaskActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskActivites__r[0] );
			}
			
			if( row.TaskAssigneeActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskAssigneeActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskAssigneeActivites__r[0] );
			}
			
			if(row.TaskCommentActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskCommentActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskCommentActivites__r[0] );
			}
			
			auxActivity.setImagePath();
			auxActivity.setHeader();
			
			projectActivities.add( auxActivity );
		}
		return projectActivities;
	}
	
	/**
	*
	*
	*/
	public static List<Task> formatTasks( List<ProjectTask__c> taskList ){
		
		List<Task> tasks = new List<Task>();
	
		for(ProjectTask__c task : taskList){
    		
    		Task taskAux = new Task();
    		
    		taskAux.id = task.id;
			taskAux.idDisplay = task.Id__c;
			taskAux.name = task.Name; 
			taskAux.isMilestone = task.Milestone__c;
			taskAux.priority = task.Priority__c; 
			taskAux.setPercentCompleted( task.PercentCompleted__c );
			taskAux.durationDisplay = String.valueOf(task.Duration__c);
			
			if( task.Milestone__c ){
				taskAux.endDateDisplay = String.valueOf(task.StartDate__c.format());
				taskAux.endDate = task.StartDate__c;
			}else{
				taskAux.endDateDisplay = String.valueOf(task.EndDate__c.format());
				taskAux.endDate = task.EndDate__c;
			}
			
			/*
    		* @todo Change ProjectMember to TaskAssignee.
    		*/
			List<ProjectMember> assignees = DAOFactory.getInstance().getAssignees(taskAux.id);
			
			taskAux.assignees = assignees;
    		
    		tasks.add(taskAux);
    		
    	}
    	
    	return tasks;
	}
}