trunk/src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MemberActivity__c.object
<CustomObject>
    <description>Object for tracking changes to Members</description>
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>MemberActivities</relationshipLabel>
        <relationshipName>MemberActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MemberActivity</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MemberActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectActivity__c.object
<CustomObject>
    <description>Object for tracking Project Changes</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <label>ProjectId</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>ProjectActivities</relationshipLabel>
        <relationshipName>ProjectActivities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>ProjectActivity</label>
    <nameField>
        <label>ProjectActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectActivities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ActivityId__c</fullName>
        <label>ActivityId</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>ProjectActivities</relationshipLabel>
        <relationshipName>ProjectActivities</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/src/objects/ProjectActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration</description>
        <label>Duration Display</label>
        <precision>13</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <displayFormat>#{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describe task status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TaskActivity__c.object
<CustomObject>
    <description>Object for tracking changes within a task</description>
    <label>TaskActivity</label>
    <nameField>
        <label>TaskActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>10</length>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>ProjectId__c</fullName>
        <label>ProjectId</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>TaskActivites</relationshipLabel>
        <relationshipName>TaskActivites</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskActivity__c.object
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>

src/objects/TaskAssigneeActivity__c.object
<CustomObject>
    <description>Object for tracking changes to task assignees</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <label>ProjectId</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>TaskAssigneeActivites</relationshipLabel>
        <relationshipName>TaskAssigneeActivites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>TaskAssigneeActivity</label>
    <nameField>
        <label>TaskAssigneeActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskAssigneeActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaskCommentActivity__c.object
<CustomObject>
    <description>Object for tracking changes to task comments</description>
    <label>TaskCommentActivity</label>
    <nameField>
        <label>TaskCommentActivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskCommentActivites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>ChangeType__c</fullName>
        <label>ChangeType</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>ModifiedBy__c</fullName>
        <label>ModifiedBy</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>ProjectId__c</fullName>
        <label>ProjectId</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipLabel>TaskCommentActivites</relationshipLabel>
        <relationshipName>TaskCommentActivites</relationshipName>
        <type>Lookup</type>
    </fields>

trunk/src/objects/TaskCommentActivity__c.object
    <fields>
        <fullName>TimeStamp__c</fullName>
        <label>TimeStamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>

src/classes/ObjectFormatter.cls
/**
* @author Matias Menafra
* @dataCreated 01/22/2010
*/
public class ObjectFormatter {

	/**
	* Constructor
	*/
	public ObjectFormatter(){
	
	}
	
	/**
	* 
	*
	*/
	public static List<Activity> formatProjectActivities( List<Activity__c> activityList ){
		
		MessageLog messageObj = new MessageLog();
		List<Activity> projectActivities = new List<Activity>();
		
		for( Activity__c row : activityList ){
			
			Activity auxActivity = new Activity();
			
			auxActivity.modifiedBy 	= row.ModifiedBy__c;
			auxActivity.action 		= row.Action__c;
			auxActivity.timestamp	= row.TimeStamp__c;
			
			if (row.ProjectActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.ProjectActivities__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.ProjectActivities__r[0] );
			}
			
			if( row.MemberActivities__r.size() != 0 ){
				auxActivity.changeType 	= row.MemberActivities__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.MemberActivities__r[0] );
			}
			
			if( row.TaskActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskActivites__r[0] );
			}
			
			if( row.TaskAssigneeActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskAssigneeActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskAssigneeActivites__r[0] );
			}
			
			if(row.TaskCommentActivites__r.size() != 0 ){
				auxActivity.changeType 	= row.TaskCommentActivites__r[0].ChangeType__c;
				auxActivity.message 	= messageObj.getMessage( row.TaskCommentActivites__r[0] );
			}
			
			auxActivity.setImagePath();
			auxActivity.setHeader();
			
			projectActivities.add( auxActivity );
		}
		return projectActivities;
	}
	
	/**
	*
	*
	*/
	public static List<Task> formatTasks( List<ProjectTask__c> taskList ){
		
		List<Task> tasks = new List<Task>();
	
		for(ProjectTask__c task : taskList){
    		
    		Task taskAux = new Task();
    		
    		taskAux.id = task.id;
			taskAux.idDisplay = task.Id__c;
			taskAux.name = task.Name; 
			taskAux.isMilestone = task.Milestone__c;
			taskAux.priority = task.Priority__c; 
			taskAux.setPercentCompleted( task.PercentCompleted__c );
			taskAux.durationDisplay = String.valueOf(task.Duration__c);
			
			if( task.Milestone__c ){
				taskAux.endDateDisplay = String.valueOf(task.StartDate__c.format());
				taskAux.endDate = task.StartDate__c;
			}else{
				taskAux.endDateDisplay = String.valueOf(task.EndDate__c.format());
				taskAux.endDate = task.EndDate__c;
			}
			
			/*
    		* @todo Change ProjectMember to TaskAssignee.
    		*/
			List<ProjectMember> assignees = DAOFactory.getInstance().getAssignees(taskAux.id);
			taskAux.assignees = assignees;
    		tasks.add(taskAux);
    	}
    	
    	return tasks;
	}
	
	/**
	*
	* @param resultList
	* @param objectType
	* @return resultList
	*/
	public static List<SearchResults> formatSearchResults( String searchTerm, List<Sobject> resultList, String objectType ){
		
		List<SearchResults> results 		= new List<SearchResults>();	
		List<Project2__c> resultsProjects 	= new List<Project2__c>();
		List<ProjectTask__c> resultsTasks 	= new List<ProjectTask__c>();
		
		if( objectType == 'project' ){
			
			resultsProjects = (List<Project2__c>) resultList;
			
			for( Project2__c iter: resultsProjects ){
				SearchResults currentResult = new SearchResults();
				
				currentResult.setName( iter.Name, searchTerm );
				currentResult.realName 		= iter.Name ;
				currentResult.iD 			= iter.Id;
				currentResult.resultType 	= 'Project';
				currentResult.setMatches( iter.Description__c, searchTerm );
				
				results.add( currentResult );
			}
		}
		
		if( objectType == 'projectTask' ){
			
			resultsTasks = (List<ProjectTask__c>) resultList;
			
			for( ProjectTask__c iter: resultsTasks ){
				SearchResults currentResult = new SearchResults();
				
				currentResult.setName( iter.Name, searchTerm );
				currentResult.realName 		= iter.Name ;
				currentResult.iD 			= iter.Id;
				currentResult.resultType 	= 'Project';
				currentResult.setMatches( iter.Description__c, searchTerm );
				
				results.add( currentResult );
			}
		}
		
		return results;
	}
	
	/**
	* 
	*
	*/
	public static List<AttachmentObj> formatAttachments( List<Attachment> attachments ){
		
		List<AttachmentObj> formattedAttachments = new List<AttachmentObj>();
		
		for( Attachment iter: attachments ){
			AttachmentObj att = new AttachmentObj();
			
			att.realId			= iter.Id;
			att.name 			= iter.Name;
			att.weight 			= String.valueOf( iter.BodyLength / 1024 ) + ' Kb';
			att.createdBy 		= iter.CreatedBy.Name;
			att.createdDate 	= iter.CreatedDate;
			
			formattedAttachments.add( att );
		}
		
		return formattedAttachments;
	} 
	
	/**
	* 
	*
	*/
	public static List<Task> formatAssigneeTask( List<ProjectAssignee__c> listOfAssignees ){
	
        Task tempTask;
        List<Task> tasks = new List<Task>(); 
        
        for( ProjectAssignee__c row : listOfAssignees ){ 
            
            tempTask = new Task();
            
            tempTask.project 			= row.project__c;
            tempTask.projectName 		= projectUtil.chopWord( row.project__r.name );
            tempTask.id 				= row.ProjectTask__c;
            tempTask.setName( ProjectUtil.chopWord( row.ProjectTask__r.name ));
            tempTask.startDate 			= row.ProjectTask__r.startDate__c; 
            tempTask.startDateDisplay 	= row.ProjectTask__r.startDate__c == null ? null : row.ProjectTask__r.startDate__c.format();
            tempTask.endDate 			= row.ProjectTask__r.endDate__c;
            tempTask.endDateDisplay 	= row.ProjectTask__r.endDate__c == null ? null : row.ProjectTask__r.endDate__c.format();
            tempTask.status 			= row.ProjectTask__r.status__c;
            tempTask.priority 			= row.ProjectTask__r.priority__c;
            tempTask.isMilestone 		= row.ProjectTask__r.milestone__c;
            tempTask.setPercentCompleted( row.ProjectTask__r.percentCompleted__c );
            tempTask.duration 			= Double.valueOf(row.ProjectTask__r.durationUI__c); 
            
            tasks.add( tempTask ); 
        }
 	
		return tasks;
	}
}