trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>DaysInWorkWeek__c</fullName>
        <description>Sets how many days in a  work week.</description>
        <inlineHelpText>1 = Mon /  7 = Sun</inlineHelpText>
        <label>Days in a work week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Sets how the Duration field will be displayed, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/UserTasksController.cls
/**
* @author Miguel Soares 
*/
public class UserTasksController{

    private Boolean showDetail;
    public id projectId;
    public id currentUser;
    public Project currentProject { set; get; }
    public List<ProjectMember__c> allProjects;
    public Map<id,ProjectMember__c> allProjectsMap;
    public List<Task> tasks {set; get;}
    public List<SelectOption> selectOpsProject;

    public String opSelected;   
    public String attachmentPrjId;
    
    // Paginator 
    public Paginator paginator 	{ set; get; }
    
    
    /**
    * Constructor
    */
    public UserTasksController(){
        
        this.projectId 		= System.currentPageReference().getParameters().get('id');
        this.currentUser 	= UserInfo.getUserId();
        this.opSelected 	= 'none'; 
        this.showDetail 	= false;

        this.allProjects 		= new List<ProjectMember__c>();
        this.tasks 				= new List<Task>();
        this.allProjectsMap 	= new Map<id,ProjectMember__c>();
        this.selectOpsProject 	= new List<SelectOption>(); 
        
		this.paginator = new Paginator();
		
		this.paginator.orderBy 		= 'Name';
		this.paginator.orderAsc 	= true;
		this.paginator.filter 		= '1'; // Show all tasks and milestones
		this.paginator.project.id 	= this.opSelected == 'none' ? '' : this.opSelected; 
		
        paginator.loadTasksByUser();
        
        this.selectAllPeojectName();
    }


    /**
    *@return String
    */
    public String getAttachmentPrjId(){
        
        if( this.allProjects == null )
            selectProjectBasicData();
        
        return this.attachmentPrjId;
    }

    /**
    * @return Boolean
    */
    public Boolean getShowDetail(){         
        
        return this.opSelected != 'none'; 
    } 

    /**
    * @return List<SelectOption>
    */
    public List<SelectOption> getProjectSelectOps(){
        
        this.selectOpsProject.clear();
        ProjectMember__c c = this.allProjects[0].clone();       
        this.selectOpsProject.add( new SelectOption( 'none', 'All projects' ) );

        for( ProjectMember__c p : this.allProjects )
            this.selectOpsProject.add( new SelectOption( (String)p.Project__c, p.Project__r.name ) );
            
        return this.selectOpsProject;
    }

    /**
    * @return String
    */
    public String getOpSelected(){
        
        this.selectProjectBasicData();
        return this.opSelected;
    }
    
    /**
    * @param String
    */
    public void setOpSelected( String op ){
        
        this.opSelected = op;
        this.paginator.project.id = op == 'none' ? '' : op;
        this.selectProjectBasicData();
    }
    
    /**
    * 
    */
    public void selectProjectBasicData(){
        
        List<String> d 					= new List<String>{'Mon', 'Thu', 'Wen', 'Thu', 'Fri', 'Sat', 'Sun'};
        this.currentProject  			= new Project();
        ProjectMember__c tempProject 	= new ProjectMember__c(); 
        
        if( this.allProjectsMap.size() > 0 && this.OpSelected != 'none' ){
            tempProject = this.allProjectsMap.get( this.OpSelected );
            
            this.AttachmentPrjId                        = tempProject.Project__r.Picture__c;
            this.currentProject.name                    = ProjectUtil.chopWords( tempProject.Project__r.name );
            this.currentProject.priority                = ProjectUtil.chopWords( tempProject.Project__r.priority__c );
            this.currentProject.displayDuration         = ProjectUtil.chopWords( tempProject.Project__r.DisplayDuration__c );
            this.currentProject.description             = ProjectUtil.chopWords( tempProject.Project__r.Description__c );
            this.currentProject.daysWorkWeekFormated    = 'Mon - ' + d[ Integer.valueOf( tempProject.Project__r.DaysInWorkWeek__c )]; 
        }
    }
    
    /**
    * @return void
    */
    public void selectAllPeojectName(){
         this.allProjects = DAOFactory.getInstance().getProjetsInfoByMember( this.currentUser );   
         
         for( ProjectMember__c p : this.allProjects)
         	this.allProjectsMap.put( p.project__c, p );
    }
}