trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Profile__c</fullName>
        <description>Profile</description>
        <label>Profile</label>
        <referenceTo>ProjectProfile__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectProfile__c.object
<CustomObject>
    <description>ProjectProfile</description>
    <label>Project Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/ProjectNewMemberController.cls
/**
*@author Ignacio Toledo 3/19/2009
*/
public with sharing class ProjectNewMemberController {

	/**
	*@constructor
	*/
	public ProjectNewMemberController (){
		if(idProject != null)
			projectName = [select Name from Project2__c where id=: idProject].Name;	
	}
	
		/**
	* Return the Namespace Prefix
	*@return String
	*/
	public String getNamespace () {
        return ProjectUtil.getNamespace();
    } 
	
	public String idProject = System.currentPageReference().getParameters().get('id');
	
	public String projectName = null;
	
	
	/**
	*@return String
	*/
	public String getProjectName () {
		return projectName;	
	}
	
	/**
	*@param String
	*/
	public void setProjectId(String s){
		idProject = s;
	}
	
	/**
	*@return String
	*/
	public String getProjectId() { 
		return idProject;	
	}

	/**
	* Load Select Menu
	*@return List<SelectOption>
	*/
	public List<SelectOption> getProfilesOptions () {
		List<SelectOption> options = new List<SelectOption>();
		for (ProjectProfile__c item: [select id, Name from ProjectProfile__c order by Name]) 
			options.add(new SelectOption(item.id,item.Name));

		return options;
	}
	
	public Member newMemberVars = new Member();
	
	/**
	*@return Member
	*/
	public Member getNewMemberVars () {
		return newMemberVars;	
	}
	
	/**
	*@param Member
	*/
	public void setNewMemberVars (Member vars) {
		this.newMemberVars = vars;
	}
	
		/**
	* Inner class for Member type
	*@class
	*/
	public class Member {
		String profileId;
		String message;
		String colleagueNames;
		
		/**
		*@return String
		*/
		public String getColleagueNames () {
			return colleagueNames;
		}
		
		/**
		*@param String
		*/
		public void setColleagueNames (String names) {
			this.colleagueNames = names;
		}
		
		/**
		*@return String
		*/
		public String getProfileId () {
			return profileId;
		}
		
		/**
		*@param String
		*/
		public void setProfileId (String profile) {
			this.profileId = profile;
		}	
		
		/**
		*@return String
		*/
		public String getMessage () {
			return message;
		}
		
		/**
		*@param String
		*/
		public void setMessage (String msj) {
			this.message = msj;
		}
		
		
	}//End class Member
	
	public void saveMembersNew () {
		List<ProjectMember__c> newMemberList = new List<ProjectMember__c>();
		List<String> newMembers = newMemberVars.colleagueNames.split(',');
		List<User> userList = new List<User>();
		Boolean already = false;
		
		for(String item: newMembers) {
			List<User> userItem = new List<User>();
			String itemTrim = item.trim();
			userItem = [select id, Name, Email from User where Name =:itemTrim limit 1];
			if (userItem.size() > 0) {
				already = false;
				Integer listPos = 0;
				while (!already && listPos < userList.size()) {
					if(userList[listPos].Name == userItem[0].Name) {
						already = true;
					}
					listPos++;
				}
				if (!already) {
					userList.add(userItem[0]);	
				}
			}
		}
		for (User user : userList) {
			Integer isMember = [select count() from ProjectMember__c where project__c =:idProject and user__c =: user.id];
			if (isMember == 0) {
				ProjectMember__c newMember = new ProjectMember__c();
				newMember.User__c = user.id;
				newMember.Name = user.Name;
				newMember.project__c = idProject;
				newMember.Profile__c = newMemberVars.profileId;
				newMemberList.add(newMember); 
				//SendMail(user,newMemberVars.message); 
			}
		}
		insert newMemberList;
		
		newMemberVars.colleagueNames = '';
		newMemberVars.profileId = '';
		newMemberVars.message = '';
	}
	
	
	public PageReference saveMembers () {
		List<ProjectMember__c> newMemberList = new List<ProjectMember__c>();
		List<String> newMembers = newMemberVars.colleagueNames.split(',');
		List<User> userList = new List<User>();
		Boolean already = false;
		
		for(String item: newMembers) {
			List<User> userItem = new List<User>();
			String itemTrim = item.trim();
			userItem = [select id, Name, Email from User where Name =:itemTrim limit 1];
			if (userItem.size() > 0) {
				already = false;
				Integer listPos = 0;
				while (!already && listPos < userList.size()) {
					if(userList[listPos].Name == userItem[0].Name) {
						already = true;
					}
					listPos++;
				}
				if (!already) {
					userList.add(userItem[0]);	
				}
			}
		}
		
		for (User user : userList) {
			Integer isMember = [select count() from ProjectMember__c where project__c =:idProject and user__c =: user.id];
			if (isMember == 0) {
				ProjectMember__c newMember = new ProjectMember__c();
				newMember.User__c = user.id;
				newMember.Name = user.Name;
				newMember.Project__c = idProject;
				newMember.Profile__c = newMemberVars.profileId;
				newMemberList.add(newMember); 
				//SendMail(user,newMemberVars.message); 
			}
		}
		insert newMemberList;
		
		newMemberVars.colleagueNames = '';
		newMemberVars.profileId = '';
		newMemberVars.message = '';
		
		PageReference pageRef = Page.ProjectMembersList;
		pageRef.getParameters().put('id', idProject);
		pageRef.setRedirect(true);
		return pageRef;	
	}
	
		
}