trunk/src/objects/ProjectSubscription__c.object
<CustomObject>
    <description>The Project Subscription Object</description>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If i have proyect task assigned to me</description>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If project task has changed</description>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Project task has been deleted</description>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectSubscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Subscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Subscription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/DAOSubscription.cls
/**
* @author Andres Canavesi
*/
public class DAOSubscription {
	
	/**
	* Constructor
	*/
	public DAOSubscription(){}
	
	
	/** Return list of project subscriptions
	*@param String idProject
	*@return List<ProjectSubscription__c>
	*/
	public List<ProjectSubscription__c> subscriptionProjectList(String idProject){
		
		return [select id,
					ProjectTaskAssignedToMe__c,
					ProjectTaskAssignToMeChanged__c,
					ProjectTaskChanged__c,
					ProjectTaskDeleted__c,
					Project__c,
					User__c
				from ProjectSubscription__c 
				where User__c =:UserInfo.getUserId() and Project__c =: idProject 
				limit 1];
		
	}
	
	/** Insert project subscription
	*@param ProjectSubscription__c subs
	*@return void
	*/
	public void insertProjectsubscription(ProjectSubscription__c subs){
		insert subs;
	}
	
	/** Updtate project subscription
	*@param ProjectSubscription__c subs
	*@return void
	*/
	public void updateProjectsubscription(ProjectSubscription__c subs){
		update subs;
	}
	
	/** Delete project subscription
	*@param ProjectSubscription__c subs
	*@return void
	*/
	public void deleteProjectsubscription(ProjectSubscription__c subs){
		delete subs;
	}
	
}