trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>DaysInWorkWeek__c</fullName>
        <description>Sets how many days in a  work week.</description>
        <inlineHelpText>1 = Mon /  7 = Sun</inlineHelpText>
        <label>Days in a work week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Sets how the Duration field will be displayed, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Picture</description>
        <label>Picture</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Assignee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DurationUI__c</fullName>
        <label>Duration</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>EndDate</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>StartDate</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describe task status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/UserDetailController.cls
public class UserDetailController{

	private Boolean showDetail;
	private id projectId;
	private id currentUser;
	private Project currentProject;
	private List<ProjectMember__c> allProjects;
	private Map<id,ProjectMember__c> allProjectsMap;
	private List<Task> tasks = new List<Task>();
	private List<SelectOption> selectOpsProject;

	public String page = '0';
	public String lastPage;
	private Integer rows = 20; 

	public Integer notShowFirst;
	public String opSelected;	
	public String attachmentPrjId;
	public Integer tasksListSize {set; get;}
	public String order {set; get;}	
	public String sortBy { set; get; }
	public Project thisProject  { set; get; }
	
	
	public UserDetailController(){
		System.debug('Construnctor ' + this.order);
		this.projectId = System.currentPageReference().getParameters().get('id');
		this.currentUser = UserInfo.getUserId();
		this.sortBy = 'projectTask__r.name';
		this.order = 'ASC';
		this.opSelected = '--None--'; 
		this.showDetail = false;

		this.allProjects = new List<ProjectMember__c>();
		this.tasks = new List<Task>();
		this.allProjectsMap = new Map<id,ProjectMember__c>();
		this.selectOpsProject = new List<SelectOption>(); 
		
		this.selectAllPeojectName();
		this.selectTasks();
	}

	/**
	*@return List<Task>
	*/
	public List<Task> getTasks(){		
		return this.tasks;
	}
	
	/**
	*@param List<Task>
	*/
	public void setTasks( List<Task> ts ){
		this.tasks = ts;		
	}

	/**
	*@return String
	*/
	public String getAttachmentPrjId(){
		if( this.allProjects == null )
		selectProjectBasicData();
		
		return this.attachmentPrjId;
		
	}

	/**
	*@return Integer
	*/
	public Integer getRows(){
		return this.rows;
	}
	
	/**
	*@return String
	*/
	public String getLastPage(){
		return String.valueOf( Integer.valueOf( this.lastPage )+1);
	}
	
	/**
	*@param String
	*/
	public void setLastPage( String lp){
		this.lastPage = lp;
	}
 
 	/**
 	*@retunr String
 	*/
	public String getPage(){
		return String.valueOf( Integer.valueOf( this.page )+1);
	}
	
	/**
	*@param String
	*/
	public void setPage( String p ){
		if( p == 'next' ){
			this.page = String.valueOf( Math.abs(Integer.valueOf( this.page )+1));
		}else if( p == 'previous' ){
			this.page = String.valueOf( Math.abs(Integer.valueOf( this.page )-1)); 
		}	
	}

	/**
	*@return Integer
	*/
	public Integer getNotShowFirst(){
		return  this.rows * Integer.valueOf( this.page ); 
	}
	
	/**
	*return Boolean
	*/
	public Boolean getShowDetail(){ 		
		return this.opSelected != '--None--'; 
	} 

	/**
	*@return ProjectMember__c
	*/
	public Project getCurrentProject(){
		return this.currentProject;
	}

	/**
	*@param ProjectMember__c
	*/
	public void setCurrentProject( Project p ){
		this.currentProject = p;
	}

	/**
	*@return List<SelectOption>
	*/
	public List<SelectOption> getProjectSelectOps(){
		this.selectOpsProject.clear();
		ProjectMember__c c = this.allProjects[0].clone();		
		this.selectOpsProject.add( new SelectOption( '--None--', 'All projects' ));

		for( ProjectMember__c p : this.allProjects )
			this.selectOpsProject.add( new SelectOption((String)p.Project__c, p.Project__r.name ));
			
		return this.selectOpsProject;
	}

	/**
	*@return String
	*/
	public String getOpSelected(){
		this.selectProjectBasicData();
		return this.opSelected;
	}
	
	/**
	*@param String
	*/
	public void setOpSelected( String op ){
		this.opSelected = op;
		this.selectProjectBasicData();
	}
	
	//Private section 	
	/**
	*@return void
	*/
	private void selectProjectBasicData(){
		List<String> d = new List<String>{'Mon', 'Thu', 'Wen', 'Thu', 'Fri', 'Sat', 'Sun'};
		this.currentProject  = new Project();
		ProjectMember__c tempProject = new ProjectMember__c(); 
		
		if( this.allProjectsMap.size() > 0 && this.OpSelected != '--None--' ){
			tempProject = this.allProjectsMap.get( this.OpSelected );
			
			this.AttachmentPrjId 					= tempProject.Project__r.Picture__c;
			this.currentProject.name 				= ProjectUtil.chopWords( tempProject.Project__r.name );
			this.currentProject.priority 			= ProjectUtil.chopWords( tempProject.Project__r.priority__c );
			this.currentProject.displayDuration 	= ProjectUtil.chopWords( tempProject.Project__r.DisplayDuration__c );
			this.currentProject.description 		= ProjectUtil.chopWords( tempProject.Project__r.Description__c );
			this.currentProject.daysWorkWeekFormated 	= 'Mon - ' + d[ Integer.valueOf( tempProject.Project__r.DaysInWorkWeek__c )];
			
		}
	}
	
	/**
	*@return void
	*/
	private void selectAllPeojectName(){
		this.allProjects = [ SELECT Project__c, Project__r.Picture__c, Project__r.name, Project__r.Description__c, Project__r.Priority__c, Project__r.DisplayDuration__c, Project__r.DaysInWorkWeek__c FROM ProjectMember__c WHERE User__c =: this.currentUser ];
		
		if( this.allProjects.size() > 0 )
		for( ProjectMember__c m : this.allProjects )
			this.allProjectsMap.put( m.Project__c, m );
	}
	
	/**
	*@return void
	*/
	public void setingOrder(){
		if( this.order == 'ASC' )
			this.order = 'DESC';
		else 
			this.order = 'ASC';		
		
		this.page = '0';
		this.selectTasks();
	}
		
	/**
	*@return void
	*/
	public void selectTasks(){
				
		String sql = 'SELECT project__c, ProjectTask__c, project__r.name, ProjectTask__r.name, ProjectTask__r.startDate__c, ProjectTask__r.endDate__c, ProjectTask__r.status__c, ProjectTask__r.priority__c, ProjectTask__r.milestone__c, ProjectTask__r.percentCompleted__c, ProjectTask__r.DurationUI__c FROM ProjectAssignee__c WHERE User__c = ';
		sql += '\'' +this.currentUser + '\'';
		
		
		if( this.opSelected != '--None--' ) 
			sql += ' AND Project__c = ' + '\'' + this.opSelected + '\'';			
			
		sql += ' ORDER BY ' + this.sortBy + ' ' + this.order;
			
		sql += ' LIMIT 1000 ';
		
		System.debug( '[>>2] ' + this.order +'<<'+sql);
		Task tempTask;
		this.tasks.clear(); 
		List<ProjectAssignee__c> chuchu = Database.query( sql );
		for( ProjectAssignee__c t : chuchu){
			tempTask = new Task();
			tempTask.project = t.project__c;
			tempTask.projectName = t.project__r.name;
			tempTask.id = t.ProjectTask__c;
			tempTask.name =  t.ProjectTask__r.name;
			tempTask.startDate = t.ProjectTask__r.startDate__c; 
			tempTask.formatedStartDate = t.ProjectTask__r.startDate__c.format();
			tempTask.endDate = t.ProjectTask__r.endDate__c;
			tempTask.formatedEndDate = t.ProjectTask__r.endDate__c.format();
			tempTask.status = t.ProjectTask__r.status__c;
			tempTask.priority = t.ProjectTask__r.priority__c;
			tempTask.isMilestone = t.ProjectTask__r.milestone__c;
			tempTask.percentComplete = t.ProjectTask__r.percentCompleted__c;
			tempTask.duration = String.valueOf( t.ProjectTask__r.percentCompleted__c );
			this.tasks.add( tempTask ); 
		}
		
		this.tasksListSize = this.tasks.size();
		this.lastPage = String.valueOf( this.tasks.size() / this.rows );
	}
}