trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Id__c</fullName>
        <displayFormat>#{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

tags/release-beta/classes/TaskQuickAccessController.cls
public class TaskQuickAccessController {

	public String taskId = '';
	public Boolean error = false;
	
	/**
	*@param s task auto id
	*/
	public void setTaskId(String s){
		taskId = '';
		if(!s.startsWith('#')){
			taskId = '#';
		}
		taskId += s;
	}
	
	/**
	*@return task auto id 
	*/
	public String getTaskId(){
		return taskId;
	}
	
	/**
	*@return error
	*/
	public Boolean getError(){
		return error;
	}
	
	/**
	*@param b error
	*/
	public void setError(Boolean b){
		error = b;
	}
	
	/**
	*@return page reference to task detail
	*/
	public PageReference go(){
		List<ProjectTask__c> tasks = new List<ProjectTask__c>();
		tasks = [select Id from ProjectTask__c where Id__c =: taskId];
		
		if(tasks.size() > 0){
			PageReference forward = new PageReference('/apex/ProjectTaskDetail?id=' + tasks[0].Id);
			forward.setRedirect(true);
			return forward;
		}else{
			error = true;
		}
		return null;
	}

}