trunk/src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>PercentDedicated__c</fullName>
        <description>PercentDedicated</description>
        <label>PercentDedicated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Assignee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/DAOAssignee.cls
/**
* @author Andres Canavesi 
* @dataCreated 12/15/2009
*/
public class DAOAssignee {
	
	/**
	* Constructor
	*/
	public DAOAssignee(){
	}
	
	/**
	* inserts an assignee
	* @param taskId
	* @param assignToId
	* @param projetId
	*/
	public void insertAssignee(String taskId, String assignToId, String projectId, Integer percentageDedicated){
		ProjectAssignee__c assignee = new ProjectAssignee__c();
		assignee.User__c = assignToId;
		assignee.ProjectTask__c = taskId;
		assignee.Project__c = projectId;
		assignee.PercentDedicated__c = percentageDedicated;
		
		insert assignee;
	}
	
	/**
	* @param task
	* @return isTaskAssigned
	*/
	//TODO change the list for a simple ProjectAssignee__c
	public Boolean isTaskAssigned(ProjectTask__c task){
		
		List<ProjectAssignee__c> assignee = [select Id
											 from ProjectAssignee__c
											 where ProjectTask__c =: task.Id
											 and OwnerId =: Userinfo.getUserId()
											 limit 1];
											 
		if(assignee.size() == 0){
			
			return true;
		}				
		
		return false;							 
	}
	
	/**
	* returns a list with all task assingees
	* @param taskId
	* @return assigneesList
	*/
	public List<ProjectMember> getAssignees(String taskId){
		List<ProjectAssignee__c> assignees = [select Id, User__r.Name, User__c
											  from ProjectAssignee__c
											  where ProjectTask__c =: taskId];
		List<ProjectMember> assigneesList = new List<ProjectMember>();
		for(ProjectAssignee__c assignee : assignees){
			ProjectMember member = new ProjectMember();
			member.id = assignee.User__c;
			member.name = assignee.User__r.Name;
			assigneesList.add(member);
		}				
		
		return assigneesList;							 
	}
}