trunk/src/objects/ProjectSetup__c.object
<CustomObject>
    <fields>
        <fullName>CanViewButtonNew__c</fullName>
        <label>CanViewButtonNew</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ListSavedProfiles__c</fullName>
        <label>ListSavedProfiles</label>
        <picklist>
            <picklistValues>
                <fullName>System Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom: Sales Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom: Marketing Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom: Support Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Platform User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Portal Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package License Manager</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>ProjectSetup</label>
    <nameField>
        <label>ProjectSetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectSetup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/DAOSetup.cls
/**
* @author Nicolas Dominguez 02/19/2010
*/
public class DAOSetup {

	/**
	* Constructor
	*/
	public DAOSetup(){
	}
	
	/**
	* Get ListSavedProfiles from ProjectSetup 
	* @return List<ProjectSetup__c>
	*/
	public List<ProjectSetup__c> getListSavedProfiles(){ 
		return [ select Id, ListSavedProfiles__c, CanViewButtonNew__c from ProjectSetup__c limit 1 ];
	}
	
	/** 
	* Insert project setup
	* @param ProjectSetup__c 
	*/
	public void insertProjectSetup( ProjectSetup__c projectSetup ){
		insert projectSetup;
	}
	
	/** 
	* Updtate project setup
	* @param ProjectSetup__c
	*/
	public void updateProjectSetup( ProjectSetup__c projectSetup ){
		update projectSetup;
	}
}