trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>Access__c</fullName>
        <description>Project Access</description>
        <inlineHelpText>Open - Anyone can join. Anyone can see the Project

Close - Administrator must invite users to join. Anyone can see the Project

Private -  This Project will not appear in search. Membership is by invitation only. Only members can see the Project.</inlineHelpText>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/ProjectActivity.cls
/**
* @author Matias Menafra 1/7/2010
*/
public class ProjectActivity extends ActivityLog{

	private String name;
	private String access;
	private Project2__c oldProject;
	private Project2__c newProject;
	
	/**
	* Constructor
	*/
	public ProjectActivity( String projectId, DateTime timeStamp, String modifiedBy, String action, String changeType, Project2__c oldProject, Project2__c newProject){
		
		super(projectId, timeStamp, modifiedBy, action, changeType);
		this.oldProject = oldProject;
		this.newProject = newProject;
	}
	
	/**
	* 
	*/
	public override void log(){
		
		if(this.oldProject.Name != this.newProject.Name){
			this.name 	= this.newProject.Name;
			//tipo de cambio
		}
		if(this.oldProject.Access__c != this.newProject.Access__c){
			this.access = this.newProject.Access__c;
			//tipo de cambio
		}
		
		DAOFactory.getInstance().logProjectActivity(this.projectId, this.timeStamp, this.modifiedBy, this.action ,this.name, this.access);
	}
}