trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Assignee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectDeleteTaskOverlayController.cls
/**
*@author Alvaro Scuccimarra @ 04/07/2009
*/
public class ProjectDeleteTaskOverlayController {
	
	private Id USERID = UserInfo.getUserId(); 
	private String idDeletes = '';
	private UserPermissions userPermissions = new UserPermissions();
	private String projectId = '';
		
	public ProjectDeleteTaskOverlayController(){} 
	 
	/**
    * Generate User Permissions
    */
    public void genPermissions () {
        userPermissions.setId(UserInfo.getUserId());
        userPermissions.setProject(projectId);
        userPermissions.setObjectType('Project');
        userPermissions.setPermissions();   
            
    }
    
    /**
    *@return idDeletes
    */
    public String getIdDeletes () {
        return idDeletes;   
    }
    
    /**
    *@param sidDeletes
    */
    public void setIdDeletes (String sidDeletes) {
        idDeletes = sidDeletes; 
    }
    
    
    public void deleteTaskFromList(){
    	deleteTask();	
    }
    
    public PageReference deleteTaskFromDetail(){
    	deleteTask();
       	PageReference pr = new PageReference('/apex/ProjectDetail?id=' + projectId);
        pr.setRedirect(true);
        return pr;
    }
    
    public void deleteTask(){
        List<String> myIds = new List<String>();
        if (idDeletes != '' && idDeletes != null){
            myIds = idDeletes.split(':'); 
        }
       
        if(myIds.size()>0){
            List<ProjectTask__c> tasksToDelete = [select (Select User__c from ProjectsAssignees__r ), id, Project__r.Id from ProjectTask__c where id in: myIds];
      		projectId = tasksToDelete[0].Project__r.Id;
      		genPermissions();
            if (tasksToDelete.size() > 0){
                List<ProjectTask__c> taskListToDelete = new List<ProjectTask__c>(); 
                for (ProjectTask__c iterTask : tasksToDelete){
                    Boolean cantEditAndDelete = false;
                    Integer countAssignee = 0;
                    while (!cantEditAndDelete && countAssignee < iterTask.ProjectsAssignees__r.size()){
                        if(iterTask.ProjectsAssignees__r[countAssignee].User__c != USERID){
                            cantEditAndDelete =  true;
                        }else {
                            countAssignee++;
                        }
                    }
                    if(!cantEditAndDelete || UserPermissions.getCanManage() || iterTask.createdById == USERID){
                        taskListToDelete.add(iterTask);
                    }else {
                        throw new CustomException('Insufficient Privileges');   
                    }
                   
                }
                if(taskListToDelete.size() > 0) {
                	delete taskListToDelete;
	            }
            }
        }
        idDeletes = '';
    }
    
}