trunk/src/objects/ProjectSubscription__c.object
<CustomObject>
    <description>The Project Subscription Object</description>
    <fields>
        <fullName>ProjectMemberJoinLeave__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If a Member join leave from Project</description>
        <label>ProjectMemberJoinLeave</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If i have proyect task assigned to me</description>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If project task has changed</description>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Project task has been deleted</description>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectSubscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Subscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Subscription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/ProjectSubscriptionControllerTest.cls
/**
*@author Miguel Soares @ 04/14/2009
*/
@isTest private class ProjectSubscriptionControllerTest {
	/**
	* Test  ProjectSubscribersEmailServices
	*@void
    *@static
	*/
    static testMethod void myUnitTest(){
    	
		GenerateEnvironmentTest.gen();
		ProjectUtil.setIsTest( true );
    	Test.startTest();
    	/*
    	System.currentPageReference().getParameters().put( 'id', GenerateEnvironmentTest.project.id );
    	ProjectSubscriptionController ps = new ProjectSubscriptionController();
    	
    	ps.setIdProject( GenerateEnvironmentTest.project.id );
    	ps.subscription.ProjectTaskChanged__c = true;
    	ps.saveSubscription();
    	ps.deleteSubscription();
    	ps.getIdProject();
    	ps.getSubscription();
    	ps.getSubscriptionCount();

    	System.currentPageReference().getParameters().put( 'id', GenerateEnvironmentTest.project.id );
    	ps = new ProjectSubscriptionController();
    	ProjectSubscription__c newS = new  ProjectSubscription__c();
    	newS.Project__c = GenerateEnvironmentTest.project.id;
    	newS.ProjectMemberJoinLeave__c = true;
    	newS.ProjectTaskAssignedToMe__c = true;
    	newS.ProjectTaskAssignToMeChanged__c = true;
    	newS.ProjectTaskChanged__c = true;
    	newS.ProjectTaskDeleted__c = true;
    	newS.User__c  = GenerateEnvironmentTest.us.id;
		insert newS;
    	ps.saveSubscription();

    	System.currentPageReference().getParameters().put( 'id', GenerateEnvironmentTest.project.id );
    	ps = new ProjectSubscriptionController();
    	ps.cancelSubscription();
*/
    	Test.stopTest();
		ProjectUtil.setIsTest( false );
    }     	
}