trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <fields>
        <fullName>DisplayDuration__c</fullName>
        <inlineHelpText>Sets how the Duration field will be displayed, in hours or days.</inlineHelpText>
        <label>Display Duration</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectAssignee__c.object
<CustomObject>
    <description>ProjectAssignee</description>
    <fields>
        <fullName>ProjectTask__c</fullName>
        <description>ProjectTask</description>
        <label>ProjectTask</label>
        <referenceTo>ProjectTask__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsAssignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Assignee</label>
    <nameField>
        <label>Assignee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Assignee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProjectMember__c.object
<CustomObject>
    <description>ProjectMember</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <description>User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectsMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Member</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectTask__c.object
<CustomObject>
    <description>ProjectTask</description>
    <fields>
        <fullName>Milestone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Milestone</description>
        <label>Milestone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PercentCompleted__c</fullName>
        <description>PercentCompleted</description>
        <label>Percent Completed</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectsTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Task</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/classes/ProjectOverlayNewTaskController.cls
/**
*@author Miguel Soares @ 03/17/2009
* refactoring for project force
*/
public class ProjectOverlayNewTaskController {
	
    public ProjectTask__c newTask = new ProjectTask__c();
   	public String PROJECTID = System.currentPageReference().getParameters().get('id'); 
   	public Project2__c currentProject = null;   
    public ProjectMember__c projectMember = new ProjectMember__c();    
   	public UserPermissions userPermissions = ProjectDetailController.userPermission.clone();
   	public String  taskPrefix = Schema.SObjectType.Projecttask__c.getKeyPrefix();
   	
   	public String domain;
   	 
    /**
    * Constructor
    */
    public ProjectOverlayNewTaskController(){
    	getCurrentProject();	
    	genPermissions();
    	
    	domain = ProjectUtil.getDomain();
	}
	
	/**
	*@return String
	*/
	public String getDomain(){
		return this.domain;
	}

   	/**
   	*@param String projectId
   	*@return void
   	*/
   	public void setProject (String projectId) {
   		this.PROJECTID = projectID;
   	}
   	
   	/**
   	* Get current project instance
   	*@return Project2__c
   	*/
   	public Project2__c getProject (){
   		return this.currentProject;
   	}
   	
   	/**
    *@return ProjectTask__c
    */
    public ProjectTask__c getTask(){
    	return this.newTask;
    }
    
	/**
	*@param ProjectTask__c value
	*@return void
	*/    
    public void setTask(ProjectTask__c value){
    	this.newTask = value;
    }
    

   
    /**
    *@return ProjectMember__c
    */
    public ProjectMember__c getProjectMember(){
    	return this.projectMember;
    }
    
    /**
    *@param ProjectMember__c value
    *@return void
    */
    public void setProjectMember(ProjectMember__c value){
    	this.projectMember = value;
    }
    
   	/**
   	*@return String
   	*/
   	public String getCurrentProjectId(){
   		return this.PROJECTID;
   	}
   	/**
   	*@return taskPrefix
   	*/
   	public String getTaskPrefix(){
   		return this.taskPrefix;
   	}
    
    /**
    * Return members select options
    *@return List<SelectOption>
    */ 
	public List<SelectOption> getProjectMembers() {
    	List<ProjectMember__c> projectMembers = new List<ProjectMember__c>();  
  	 	List<SelectOption> options = new List<SelectOption>();
  	 	if(PROJECTID != null){
	  	 	projectMembers = [Select t.Project__c, t.User__r.Name, t.User__r.IsActive, t.Name, t.User__c, t.Id 
	  	 						from ProjectMember__c t 
	  	 						where t.Project__c =: PROJECTID and t.User__r.IsActive != false];  
	  	 	options.add(new SelectOption('-1', 'Choose a project Member'));
	  	 	for(ProjectMember__c c: projectMembers) {
    			options.add(new SelectOption(c.User__c, c.User__r.Name)); 
	 		}
  	 	}
  	 	return options;
   	}

	/**
	* Read Project for current project
	*@return void
	*/
	public void getCurrentProject(){   
		if(PROJECTID != null)
			currentProject = [select p.Id, p.Name, p.DisplayDuration__c 
								from Project2__c p 
								where p.Id =: PROJECTID 
								limit 1];
	}
	
	
	/**
	* For rerender use
	*@return void
	*/
	public void dummyRefresh (){}   
	
	
	/**
	* Read user permissions
	*@return void
	*/
	public void genPermissions () {
		userPermissions.setId(UserInfo.getUserId());
		userPermissions.setProject(PROJECTID);
		userPermissions.setObjectType('Project');
		userPermissions.setPermissions();		
	}
   	
   	/**
   	* Create new task
   	*@throws CustomException message Insufficient Privileges
	*@return void
   	*/
   	public void insertTask (){ 
   		
   		//Read Permissions
   		genPermissions();
   		
   		if(!userPermissions.getCanCreate()){
        	throw new CustomException('Insufficient Privileges');
   		}else{	
   			
   			ProjectUtil.setFlagAssignee( false );
   			newTask.Milestone__c = false;
			newTask.Project__c = PROJECTID;
			newTask.PercentCompleted__c = 0.0;
			newTask.Priority__c = 'Medium';
			insert newTask; 

	  		ProjectAssignee__c Assign = new ProjectAssignee__c();
			Assign.User__c = projectMember.User__c;
			Assign.ProjectTask__c = newTask.Id;
			Assign.Project__c = newTask.Project__c;
			insert Assign;
			
			newTask = new ProjectTask__c();
			Assign = new ProjectAssignee__c();
   		}
   		 //To reset the selectList
		projectMember.User__c=null;
   	}
}