trunk/src/objects/Project2__c.object
<CustomObject>
    <description>Project2</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

trunk/src/objects/ProjectSubscription__c.object
<CustomObject>
    <description>The Project Subscription Object</description>
    <fields>
        <fullName>ProjectTaskAssignToMeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProjectTaskAssignToMeChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskAssignedToMe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If i have proyect task assigned to me</description>
        <label>ProjectTaskAssignedToMe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If project task has changed</description>
        <label>ProjectTaskChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjectTaskDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Project task has been deleted</description>
        <label>ProjectTaskDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project</description>
        <label>Project</label>
        <referenceTo>Project2__c</referenceTo>
        <relationshipName>ProjectSubscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Subscription</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Subscription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/src/classes/ProjectSubscriptionController.cls
/**
*@author Ignacio Toledo @ 30/03/2009
*/
public class ProjectSubscriptionController {
	
	public String idProject = System.currentPageReference().getParameters().get('id');
	public Integer subscriptionCount; 
	public ProjectSubscription__c subscription = new ProjectSubscription__c();
	
	
	/**
	* Constructor
	*/
	public ProjectSubscriptionController () {
		constructMethods(); 
	}
	
	
	/**
	*@return String
	*/
	public String getNameProject(){
		String pName = [ select Id, Name from Project2__c where Id =: idProject limit 1 ].Name;
		if( pName.length() > 24 )
		pName = pName.substring( 0, 23 );
		return pName;	
	}
	
	/**
	*@return Integer
	*/
	public Integer getSubscriptionCount () {
		return subscriptionCount;
	}
	
	/**
	*@return ProjectSubscription__c
	*/
	public ProjectSubscription__c getSubscription () {
		return subscription;
	}
	
	/**
	*@param String idProject
	*@return void
	*/
	public void setIdProject (String idProject) {
		this.idProject = idProject; 
	}
	
	/**
	*@return String
	*/
	public String getIdProject () {
		return idProject;
	}

	/**
	* Execute on Construct
	*@return void
	*/
	public void constructMethods () {
		if (idProject != null) {
			List<ProjectSubscription__c> teamSubList = new List<ProjectSubscription__c>();
			teamSubList = [select id,
							ProjectTaskAssignedToMe__c,
							ProjectTaskAssignToMeChanged__c,
							ProjectTaskChanged__c,
							ProjectTaskDeleted__c,
							Project__c,
							User__c
						from ProjectSubscription__c 
						where User__c =:UserInfo.getUserId() and Project__c =: idProject 
						limit 1];
						
			if (teamSubList.size() > 0 ) {
				subscription = teamSubList[0];
			}	
			subscriptionCount = teamSubList.size();
		}
	}
	
	/**
	* Save suscription
	*@return PageReference
	*/
	public PageReference saveSubscription () {
		if (subscriptionCount > 0) {
			update 	subscription;	
		}else {
			subscription.Project__c = idProject;
			subscription.User__c = UserInfo.getUserId();
			insert subscription;
		}
		PageReference pageRef = Page.ProjectDetail;
		pageRef.getParameters().put('id', idProject);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	/**
	* Cancel suscription
	*@return PageReference
	*/
	public PageReference cancelSubscription () {
		PageReference pageRef = Page.ProjectDetail;
		pageRef.getParameters().put('id', idProject);
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	/**
	* Delete subscription
	*@return PageReference
	*/
	public PageReference deleteSubscription () {
		if (subscription != null && subscriptionCount > 0 ) 
			delete subscription;
		
		PageReference pageRef = Page.ProjectDetail;
		pageRef.getParameters().put('id', idProject);
		pageRef.setRedirect(true);
		return pageRef;
	}
}